### ISSUE TITLE
Ignore scheduling if DESTALINATOR_RUN_ONCE is used

### ISSUE THREAD

**Issue by dshackith** [randsleadershipslack/destalinator#156]
Scheduler still cares about local timezone on container/server and will fail if not set, even if DESTALINATOR_RUN_ONCE is set. All scheduling should be ignored (and code not run) if DESTALINATOR_RUN_ONCE is set.

This is relevant when running Destalinator as a Kubernetes ChronJob that handles the scheduling.

**Comment by kmarekspartz** [comment]
Relevant lines: https://github.com/randsleadershipslack/destalinator/blob/master/scheduler.py#L47

My guess is you updated settings.yml to remove schedule_hour?

**Comment by dshackith** [comment]
I have `DESTALINATOR_SCHEDULE_HOUR=5` set in the environment, and configuration.yaml still contains `schedule_hour: 4`. The code does not seem to allow for no schedule, if I am using scheduler.py, but that is the only place where RUN_ONCE is detected.

**Comment by kmarekspartz** [comment]
Interesting... what is the error message you're getting?

**Comment by dshackith** [comment]
> Traceback (most recent call last):
  File "scheduler.py", line 25, in <module>
    @sched.scheduled_job("cron", **schedule_kwargs)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 371, in inner
    next_run_time, jobstore, executor, True, **trigger_args)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 330, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 782, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 768, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/triggers/cron/__init__.py", line 48, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/util.py", line 80, in astimezone
    raise ValueError('Unable to determine the name of the local timezone -- use an explicit timezone instead')
ValueError: Unable to determine the name of the local timezone -- use an explicit timezone instead

**Comment by kmarekspartz** [comment]
Very weird. This is with something like `docker run -it -e DESTALINATOR_RUN_ONCE=true destalinator` ?

**Comment by dshackith** [comment]
Exactly. But, there are a couple other differences:
1. I am using python:alpine3.6 for the base
2. I have added tini for zombie reaping (see https://github.com/krallin/tini)

**Comment by kmarekspartz** [comment]
Looks related to https://github.com/agronholm/apscheduler/issues/87. I don't think this bug has anything to do with RUN_ONCE, but we could skip the scheduler all together and avoid this with RUN_ONCE.

**Comment by dshackith** [comment]
Also fixed by setting /etc/timezone in Dockerfile: https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

**Comment by dshackith** [comment]
But I still don't think the scheduler should care about timezone if no scheduling is being done.

**Comment by kmarekspartz** [comment]
Agreed. Sending a MR shortly.

**Comment by kmarekspartz** [comment]
MR: #157
