### ISSUE TITLE
Channels named #ಠ_ಠ break the destalinator

### ISSUE THREAD

**Issue by zeckalpha** [randsleadershipslack/destalinator#96]
```2017-06-01T14:03:14.674114+00:00 app[clock.1]: Traceback (most recent call last):
2017-06-01T14:03:14.674115+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/apscheduler/executors/base.py", line 112, in run_job
2017-06-01T14:03:14.674128+00:00 app[clock.1]:     retval = job.func(*job.args, **job.kwargs)
2017-06-01T14:03:14.674129+00:00 app[clock.1]:   File "scheduler.py", line 24, in destalinate_job
2017-06-01T14:03:14.674130+00:00 app[clock.1]:     scheduled_warner.warn()
2017-06-01T14:03:14.674131+00:00 app[clock.1]:   File "/app/warner.py", line 11, in warn
2017-06-01T14:03:14.674132+00:00 app[clock.1]:     self.ds.warn_all(self.config.warn_threshold, force_warn)
2017-06-01T14:03:14.674132+00:00 app[clock.1]:   File "/app/destalinator.py", line 243, in warn_all
2017-06-01T14:03:14.674133+00:00 app[clock.1]:     if self.warn(channel, days, force_warn):
2017-06-01T14:03:14.674134+00:00 app[clock.1]:   File "/app/destalinator.py", line 162, in warn
2017-06-01T14:03:14.674135+00:00 app[clock.1]:     if self.slacker.channel_has_only_restricted_members(channel_name):
2017-06-01T14:03:14.674136+00:00 app[clock.1]:     print("mids for {} is {}".format(channel_name, mids))
2017-06-01T14:03:14.674136+00:00 app[clock.1]:   File "/app/slacker.py", line 165, in channel_has_only_restricted_members
2017-06-01T14:03:14.674137+00:00 app[clock.1]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u0ca0' in position 0: ordinal not in range(128)```

**Comment by zeckalpha** [comment]
I worked around this bug by manually archiving this channel for now.

**Comment by rossnz** [comment]
I have a similar issue, someone has created a channel containing the unicode character u'\xf1' (ñ).

`Traceback (most recent call last):
  File "./warn_and_archive.py", line 9, in <module>
    warn_and_archive_warner.warn()
  File "/home/centos/destalinator/warner.py", line 11, in warn
    self.ds.warn_all(self.config.warn_threshold, force_warn)
  File "/home/centos/destalinator/destalinator.py", line 254, in warn_all
    if self.stale(channel, days):
  File "/home/centos/destalinator/destalinator.py", line 142, in stale
    self.debug("Channel #{} is not yet of minimum_age; skipping stale messages check".format(channel_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 16: ordinal not in range(128)`

**Comment by zeckalpha** [comment]
It looks like this has been fixed since switching to using logging's built in formatters. @rossnz Can you pull master and try again?

`./warn_and_archive.py` was also removed in favor of setting `export DESTALINATOR_RUN_ONCE=true` and running the scheduler.

**Comment by zeckalpha** [comment]
Hmm it helps if I save the file before I run the tests. Still occurring.

**Comment by zut7** [comment]
Still happening.
